index:
   path: /signup
   controller: App\Controller\UserController::index
search_discussion:
    path: /searchdiscussion
    controller: App\Controller\DiscussionController::searchDiscussionByUsername
    methods: [GET]
